# Generated by Django 4.0.4 on 2022-04-13 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.IntegerField()),
                ('sname', models.CharField(max_length=100)),
                ('smail', models.EmailField(max_length=254)),
                ('sadd', models.CharField(max_length=200)),
            ],
        ),
    ]
